<a href="https://colab.research.google.com/github/suyeonlee333333/oss2025/blob/main/%EC%9D%B4%EC%83%81%EC%B9%98_%EC%A0%9C%EA%B1%B0_%EC%8B%A4%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd

data = np.array([10, 12, 14, 15, 18, 100, 13, 11, 12, 14, 13, 12, 15])

df = pd.DataFrame(data, columns=['data'])

q3_data = df['data'].quantile(q=0.75)
q1_data = df['data'].quantile(q=0.25)
iqr_data = q3_data - q1_data

upper_bound = q3_data + 1.5 * iqr_data
lower_bound = q1_data - 1.5 * iqr_data

outliers = df[(df['data'] > upper_bound) | (df['data'] < lower_bound)]

clean_data = df[(df['data'] <= upper_bound) & (df['data'] >= lower_bound)]['data']

data_min = np.min(clean_data)
data_max = np.max(clean_data)
normalized = (clean_data - data_min) / (data_max - data_min)

mean = np.mean(clean_data)
std = np.std(clean_data)
standardized = (clean_data - mean) / std

print("이상치 제거 전:\n", data)
print("\n이상치 제거 후:\n", clean_data.values)
print("\n표준화 결과:\n", standardized.values)
print("\n정규화 결과:\n", normalized.values)

이상치 제거 전:
 [ 10  12  14  15  18 100  13  11  12  14  13  12  15]

이상치 제거 후:
 [10 12 14 15 18 13 11 12 14 13 12 15]

표준화 결과:
 [-1.58820278 -0.61084722  0.36650833  0.85518611  2.32121944 -0.12216944
 -1.099525   -0.61084722  0.36650833 -0.12216944 -0.61084722  0.85518611]

정규화 결과:
 [0.    0.25  0.5   0.625 1.    0.375 0.125 0.25  0.5   0.375 0.25  0.625]
